apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bishoysoliman-ingress
  namespace: bishoy-personalsite
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - www.bishoysoliman.com
    - bishoysoliman.com
    secretName: letsencrypt-account-key
  rules:
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: personalsite
            port: 
              number: 3000