apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bisaak-ingress
  namespace: bishoy-personalsite
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - hosts:
    - www.bisaak.com
    secretName: tls-secret
  rules:
  - host: www.bisaak.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: personalsite
            port: 
              number: 3000