name: ci deploy production

concurrency:
    group: production
    cancel-in-progress: true

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to production"
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: bash ~/projects/bishoy-personal/start.sh